spring:
  main:
    web-application-type: none
  cloud.stream:
    function:
      definition: produceAudioTagCreated;consumeAudioTagProcessed
      bindings:
        produceAudioTags-out-0: audio-tag
    bindings:
      audio-tag:
        destination: ${KAFKA_AUDIO_TAG_CREATED_TOPIC:audio-tag-created}
    default-binder: kafka
    kafka:
      binder:
        brokers: ${KAFKA_SERVER:localhost:9092}
tag:
  delimiter:
    genre: ${GENRE_DELIMITER:;}