spring:
  main:
    web-application-type: none
  cloud.stream:
    function:
      definition: produceAudioTagCreated;consumeAudioTagProcessed
      bindings:
        produceAudioTagCreated-out-0: audio-tag-created
        consumeAudioTagProcessed-in-0: audio-tag-processed
    bindings:
      audio-tag-created:
        destination: ${KAFKA_AUDIO_TAG_CREATED_TOPIC:audio-tag-created}
      audio-tag-processed:
        destination: ${KAFKA_AUDIO_TAG_PROCESSED_TOPIC:audio-tag-processed}
    default-binder: kafka
    kafka:
      binder:
        brokers: ${KAFKA_SERVER:localhost:9092}
tag:
  delimiter:
    genre: ${GENRE_DELIMITER:;}